-- MySQL Script generated by MySQL Workbench
-- gio 28 dic 2023, 17:26:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ISPW
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `ISPW` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ISPW` ;



-- -----------------------------------------------------
-- Table `ISPW`.`GIORNALE`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `ISPW`.`GIORNALE` (
  `titolo` VARCHAR(200) NULL DEFAULT NULL,
  `categoria` VARCHAR(10) NULL DEFAULT 'QUOTIDIANO',
  `lingua` VARCHAR(10) NULL DEFAULT NULL,
  `editore` VARCHAR(200) NULL DEFAULT NULL,
  `dataPubblicazione` DATE NULL DEFAULT NULL,
  `copieRimanenti` INT NULL DEFAULT NULL,
  `disp` INT NULL DEFAULT NULL,
  `prezzo` FLOAT NULL DEFAULT NULL,
  `idGiornale` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idGiornale`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

