-- MySQL Script generated by MySQL Workbench
-- gio 28 dic 2023, 17:26:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ISPW
-- -----------------------------------------------------


CREATE SCHEMA IF NOT EXISTS `ISPW` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ISPW` ;


-- -----------------------------------------------------
-- Table `ISPW`.`NEGOZIO`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `ISPW`.`NEGOZIO` (
  `idNegozio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `via` VARCHAR(100) NULL DEFAULT NULL,
  `isValid` TINYINT(1) NULL DEFAULT NULL,
  `isOpen` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idNegozio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




