-- MySQL Script generated by MySQL Workbench
-- gio 28 dic 2023, 17:26:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ISPW
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `ISPW` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ISPW` ;



-- -----------------------------------------------------
-- Table `ISPW`.`PAGAMENTO`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `ISPW`.`PAGAMENTO` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `metodo` VARCHAR(10) NULL DEFAULT NULL,
  `nomeUtente` VARCHAR(20) NULL DEFAULT NULL,
  `spesaTotale` FLOAT NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `tipoAcquisto` VARCHAR(50) NULL DEFAULT NULL,
  `idProdotto` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


