-- MySQL Script generated by MySQL Workbench
-- gio 28 dic 2023, 17:26:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ISPW
-- -----------------------------------------------------



CREATE SCHEMA IF NOT EXISTS `ISPW` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ISPW` ;

-- -----------------------------------------------------
-- Table `ISPW`.`USERS`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `ISPW`.`USERS` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `idRuolo` VARCHAR(1) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `cognome` VARCHAR(40) NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `pwd` VARCHAR(16) NULL DEFAULT NULL,
  `descrizione` TEXT NULL DEFAULT NULL,
  `dataNascita` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;






